### PR TITLE
Enable parallel testing

### PR DESCRIPTION
**Pull request by joshpencheon**
This PR makes a number of changes to the test suite in order to allow it to run in parallel using the Rails 6 parallelism mechanism (multiprocess, fork-based).

- [x] target flakey test
- [x] refactor schema tests to use ephemeral location + cleanup
- [x] address chrome driver modal issues
- [x] enable parallel testing by default

### CODE REVIEW

**Comment by joshpencheon** [comment]
The chrome modal issues I was seeing appeared to to go away when I allowed more leeway in capybara's wait timeout - presumably Chrome was bogging down a bit.

**Comment by joshpencheon** [comment]
Sample runs, anecdotal only...

Before: 

```
$ PARALLEL_WORKERS=1 bin/rails test
Finished in 1556.693891s, 0.6103 runs/s, 3.4098 assertions/s.
950 runs, 5308 assertions, 0 failures, 0 errors, 13 skips
```

After: 

```
$ PARALLEL_WORKERS=2 bin/rails test
Finished in 731.754351s, 1.2982 runs/s, 7.2538 assertions/s.
950 runs, 5308 assertions, 0 failures, 0 errors, 13 skips
```

**Review by kenny-lee-1 — COMMENTED** [review]
I know schema test is slow but is still the full end to end test of a schema build

**Review by kenny-lee-1 — APPROVED** [review]

**Comment by joshpencheon** [comment]
I'm ignoring the remaining rubocop reports, to avoid refactoring working code.

**Comment by joshpencheon** [comment]
Out of interest @kenny-lee-1 / @ollietulloch - I ran this on my workstation (12 vcpus) and test runs take ~200 seconds. The limiting factor appears to be the schema pack assembling, which has to run once per worker that runs any tests from that file.

**Pull request merged**
