### PR TITLE
Allow Application update via PDF submission [#26787]

### PR DESCRIPTION
**Pull request by miles-smith**
This PR adds support for updating existing applications via subsequent PDF form submission.

- Allow PdfApplicationFacade to be used with persisted projects [#26787]
- Parameterize and prep project import form for reuse [#26787]
- Display import form on project edit page [#26787]
- Fix import form margin/spacing issues [#26787]
- Add upload guidance for pdf based updates [#26787]
- Plumb in routes/controller for project update via PDF [#26787]

### CODE REVIEW

**Comment by miles-smith** [comment]
*Full disclosure* 
Whatever it is in the test suite that causes unpredictability in test results has been rearing its head in `tests/facades/pdf_application_facade_test.rb`. 

When run in isolation, that test file has appeared consistently green for me locally but when run as part of the full test suite I'm sometimes seeing failures (IIRC `should assign associated lawful bases` - `assert_equal` on a new collection, expected 1, actual 6). It seems more noticeable on CI too - I've run the test job 3 or 4 times now and only the final time has it gone green.

I'm going to try and find some time to go bug hunting through the test suite...

**Review by kenny-lee-1 — APPROVED** [review]

**Review by kenny-lee-1 — APPROVED** [review]
Do failing CI seeds consistently fail locally?

**Comment by miles-smith** [comment]
A few more observations:
- seed 14668 seems to result in the test failing more often than not (but still not 100% of the time).
- unaffected by parallelism; setting the worker count to 1 does not remedy the issue.

**Comment by miles-smith** [comment]
Ah! I think I see the issue... shared state.

I'm kinda kicking myself for a) not spotting it earlier, and b) making the mistake in the first place.

**Review by kenny-lee-1 — APPROVED** [review]
good 👀

**Pull request merged**
