### PR TITLE
Add a migration to change name value in Organisation Type with id of 1

### PR DESCRIPTION
**Pull request by JoeCatling**

### CODE REVIEW

**Review by ollietulloch — DISMISSED** [review]
Thanks @JoeCatling - looks good

**Comment by JoeCatling** [comment]
> Thanks @JoeCatling, you seem to have added an additional migration `20201210150402` - is this local to you?

Migration on old branch has now been rolled back so fixed for this PR and shouldn't cause any issues in future.

**Review by ollietulloch — COMMENTED** [review]
Thanks @JoeCatling - there are a couple of rubocop issues in the migration file, could you address those please?

**Review by ollietulloch — APPROVED** [review]
Thanks @JoeCatling - looks good

**Pull request merged**
