### PR TITLE
Brca codebase refactoring

### PR DESCRIPTION
**Pull request by FrancescoNea**
Refactored some brca core code, in order to try resolve some rails auto and eager loading issues.

### CODE REVIEW

**Review by joshpencheon — COMMENTED** [review]
I've gone a bit further, and actually swapped the code loader over to the modern `zeitwerk` + enabled eager-loading of the `lib/` directory.

This has lead to a few observations:

* `lib/` contained a few ruby script files, which I've moved to `script/`
* generally, all the local `require` statements should not be needed; the autoloader should be able to figure it out. For now, I've done bulk commenting, but we could/should clean up.
* there were "deprecated" versions of certain files, defining the same classes. I've renamed these classes to reflect their deprecated statuses. Similar story for a "...new2" Sheffield file.
* Following on from the point above, I get the impression that some of the code here is not being used anymore... it'd be great to delete what we can, to reduce the maintenance burden.

**Comment by joshpencheon** [comment]
@FrancescoNea thank you!

I've made a whole host more changes; tests are still passing for me, but was wondering if you had any additional BRCA checks you were doing to test things were still working?

**Comment by FrancescoNea** [comment]
> @FrancescoNea thank you!
> 
> I've made a whole host more changes; tests are still passing for me, but was wondering if you had any additional BRCA checks you were doing to test things were still working?

Thank you for this @joshpencheon! Not at the moment. Some coverage tests needs to be implemented. What I do at the moment is to compare some db tables (including _ad-hoc_ built ones) before and after changes, to see if changes actually disrupted the 'canonical' extraction and storing of information

**Comment by FrancescoNea** [comment]
> This has lead to a few observations:
> 
> * `lib/` contained a few ruby script files, which I've moved to `script/`
> * generally, all the local `require` statements should not be needed; the autoloader should be able to figure it out. For now, I've done bulk commenting, but we could/should clean up.
> * there were "deprecated" versions of certain files, defining the same classes. I've renamed these classes to reflect their deprecated statuses. Similar story for a "...new2" Sheffield file.
> * Following on from the point above, I get the impression that some of the code here is not being used anymore... it'd be great to delete what we can, to reduce the maintenance burden.

Thank you @joshpencheon :) 

- do you mean accessory sql and sh scripts in both lib/import/brca/scripts and lib/import/colorectal/scripts ?
- Agree. I am more than happy to do some clear-up duty
- Thank you for this. I realise now that it could have been interfered with the class loading. Thank you for picking this up!
- There are some scripts that are not automatically used by the whole pipeline, but are commodity scripts that allow the user to perform some custom actions (i.e. beautify from pseudo to csv). I will give them a look and perhaps will move them to a more convenient place? Deprecated scripts will be deleted so to have a clean version of the pipeline

**Comment by joshpencheon** [comment]
The scripts I moved were `script/pseudonymised_file_converter.rb` and `script/load_prescr_pg.rb`; guessing only the former was perhaps relevant to your BRCA work.

The issue with having scripts in `lib/` is that when lib gets eager loaded in production, those scripts will actually be executed (which might have weird side effects, but in the case of one of them was actually killing Rails).

**Comment by joshpencheon** [comment]
(non-Ruby files I didn't move, as they don't interfere with the code loading... but they might also be more conventionally homed in `script/` rather than `lib/`. 🙂)

**Comment by FrancescoNea** [comment]
Dear @joshpencheon and @ollietulloch,

I have pulled Josh commits and tested:

- Numbers before and after refactoring for both normal and abnormal test results for both BRCA and Colorectal importers
- Tested that information extracted from genetic_test_results table didn't change after refactoring BRCA code base and after latest commits

All tests were successful, and I am therefore happy with the results.

If you wish so, I think this PR could be merged with master branch

I will perform a sweep of unused / redundant scripts in a separate branch after this PR gets accepted

Thank you both for this!

**Comment by joshpencheon** [comment]
That’s great, thanks @FrancescoNea - I’ll give it one more 👀 in the morning and then we can merge 💪

**Review by joshpencheon — APPROVED** [review]
Thanks for all your work testing this @FrancescoNea , I've approved the PR now.

Would you like to merge this in? I Recommend you use the "squash and merge" option :)

**Pull request merged**
