### PR TITLE
CI: try and cache the bundle between builds

### PR DESCRIPTION
**Pull request by joshpencheon**
It currently takes ~5 minutes of compute time per job to do this.

This PR uses caching functionality provided by the default `setup-ruby` action to preserve a cache of the installed + built gems between runs.

### CODE REVIEW

**Comment by joshpencheon** [comment]
I'll restart the builds once done, to see what effect there is.

**Comment by joshpencheon** [comment]
Although the caching worked, it would appear that the version of `sassc` being used made use of some very CPU-specific features during the native install. The upshot being that the bundle cache key was not granular enough, and builds using the cache could fail depending on the CPU they were scheduled against. More recent `sassc` versions apparently build in a slightly more flexible way.

**Comment by joshpencheon** [comment]
It would seem the "Ruby + Bundle" drops to <10s with maximal use of the cache. Even if there are some changes to the bundle in a commit, the unchanged portion still benefits from the cache too. :)

**Review by ollietulloch — APPROVED** [review]
Thanks @joshpencheon - looks good, now seeing checks (eg `Test / brakeman (push)`) in ~25 seconds instead of ~5 minutes

**Pull request merged**
